### ISSUE TITLE
[🚀 feat] 거래 제안 기능 구현

### ISSUE THREAD

**Issue by shin-mallang** [2023-Wns-One-And-A-Half/backend#13]
- [x] 판매자가 자신의 판매글에 신청할 수 없음
- [x] 중복 신청 불가
- [x] 상품에 대해 구매요청을 보냈는지 여부도 반환하는 API 작성

<br/>

## TODO 

- [ ] 이미 거래된 상품이면 예외
  - [ ] #14  구현 후 구현

<br/>

- [ ] 블랙리스트로 등록되는 경우 구매 신청 내역도 다 취소되어야 함
- [ ] 블랙리스트는 어차피 로그인 불가에 세션정보 만료시킬거라 신청못함
- [ ] #9
